name: Essential Weather Alert
on:
  schedule:
    - cron: '0 6 * * *'  # 6AM UTC
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-dev libxss1
          pip install pywhatkit requests geopy
          
      - name: Run script with virtual display
        run: |
          xvfb-run -a python weather_update.py
        env:
          RECIPIENT_NUMBERS: ${{ secrets.RECIPIENT_NUMBERS }}
          DISPLAY: :99  # Required for headless operation
